### ISSUE TITLE
ELIFECYCLE

### ISSUE THREAD

**Issue by daarmstrong** [niklasravnsborg/front-export#1]
Hi when i try to run your script it errors out on ELIFECYCLE.
Do you know why this may be occuring?

**Comment by niklasravnsborg** [comment]
No I don't know. Please provide me with exact information about what you have done and how you configured the script. Then give me the complete error message. Thanks.

**Comment by daarmstrong** [comment]
Hello, thanks for getting back to me.

![image](https://user-images.githubusercontent.com/37885928/38160659-f4cc96d6-34f3-11e8-935b-eea2bc17582f.png)
[2018-03-31T06_56_59_278Z-debug.log](https://github.com/niklasravnsborg/front-export/files/1865227/2018-03-31T06_56_59_278Z-debug.log)

I have attached a screenshot and the log.
I have followed your instructions but when i type run it says Failed at the front-export@2.2.0 start script.

does this help?

**Comment by niklasravnsborg** [comment]
Can you try the following:

Run this command first: `npm install`

Then try again and let me know if it works!

**Comment by daarmstrong** [comment]
Hey,

Thanks for getting back to me.

I tried doing this and it’s still failing.

[cid:image001.png@01D3CB46.86B897B0]

I don’t know if you notice it saying it does not recognise the ‘.’ As a command – could this be causing the problem?

Thanks,

David



Please like our facebook page: www.facebook.com/cruisefinder.com.au<http://www.facebook.com/cruisefinder.com.au>

[cid:Cruisefinder-logoBICTON_476df7c8-6310-4632-9709-2acca5fabbb2.jpg]


David Armstrong
Travel Consultant | IT Manager
CLIA Accredited Cruise Consultant
P: 1800 074 477 | F: (08) 6311 7499
E: david@cruisefinder.com.au | W: www.cruisefinder.com.au<http://www.cruisefinder.com.au/>
A: New Office - 259 Canning Hwy (corner Petra Street),East Fremantle,Western Australia,6158
[cid:Facebook_ee63a854-e7d1-4869-98a9-f8e155ad3f36.png]<https://www.facebook.com/cruisefinder.com.au> [cid:Youtube_712b96f1-5dfe-4b54-ae75-6992adf4dbbd.png] <https://www.youtube.com/user/cruisefindertv/playlists> <https://www.youtube.com/user/cruisefindertv/playlists>


<http://www.trybooking.com/rqsd>[cid:EmailTemplateJPG2018V2_67c133d6-b1c0-492c-b0b7-075bc3e07ef1.jpg]<http://www.trybooking.com/RQSD>

________________________________
Disclaimer: This message and any files transmitted with it are intended for and should only be read by the intended addressee.
Its contents are confidential and if you are not the intended addressee, please notify the sender immediately and delete all records of the message from your computer.
Any reproduction, dissemination, copying, disclosure, modification and distribution of this message, without written consent of the sender is strictly prohibited.
The contents of this communication represent the sender's personal views and opinions, which do not necessarily reflect those of Bicton Travel PTY LTD and its subsidiaries.
We have taken precautions to minimise the risk of transmitting viruses, but we advise you to carry out your own virus checks. We cannot accept liability for any loss or damage caused by software viruses.

Winners of the 2016, 2015 & 2014 AFTA Agency of the Year
Winners of the 2017, 2016, 2015, 2014, 2013, 2011 & 2010 CLIA Cruise Industry Awards “Cruise Agency of the Year”
Winners of the 2017, 2016, 2015, 2014 & 2013 Cruise Passenger Magazine Readers Choice Awards "Best Travel Agency"

**Comment by niklasravnsborg** [comment]
I can't see your image. Please answer on GitHub

**Comment by daarmstrong** [comment]
hi, sorry about that.

Here is the screenshot where it says '.' is not a recognised command.

![capture](https://user-images.githubusercontent.com/37885928/38296824-232dfa7c-3825-11e8-8b15-c3d1c182daff.PNG)

**Comment by daarmstrong** [comment]
Any other ideas?

**Comment by niklasravnsborg** [comment]
I didn't test it on Windows. Maybe try on macOS or Linux. The file handling behaves differently there.

**Comment by daarmstrong** [comment]
ok.
So i tried on linux.
Now saying cant find the .env file which i have saved in the main directory :(
Sorry to be a pain new to all this as you can already tell.

**Comment by daarmstrong** [comment]
the file i have called token.env and has this code in it
FRONT_JSON_WEB_TOKEN: my_token

**Comment by niklasravnsborg** [comment]
Use a equal sign instead of the colon:

`FRONT_JSON_WEB_TOKEN=find_your_token_in_the_front_settings`

**Comment by daarmstrong** [comment]
ok I am about to give up.... got that to work now it's saying this:

> front-export@2.2.0 start /home/david/Downloads/front-export-master
> ./bin/index.js "theteam@cruisefinder.com.au"

TypeError: Cannot read property 'status' of undefined
    at axios.interceptors.response.use.err (/home/david/Downloads/front-export-master/lib/api.js:23:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

**Comment by daarmstrong** [comment]
Any other ideas?

**Comment by niklasravnsborg** [comment]
Unfortunately not. Because I can't reproduce since I don't have a Front account anymore. I can offer to test it with your private key if you reach out to me via twitter or email. Hope to help you that way. Please excuse my late answer.

**Comment by daarmstrong** [comment]
Hi,

That would be great if you could.
What is your email?

Thanks,

David

**Comment by niklasravnsborg** [comment]
Use the one from my git commits. Will not post it publicly here because of spam.
